services:
  run-react-app-dev:
    container_name: pathfinder-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: ./
        target: /app
        consistency: delegated
      - type: volume
        target: /app/node_modules